version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - polar-net
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: recording-api
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/recordingdb
    depends_on:
      - mongo
    networks:
      - polar-net

volumes:
  mongo-data:

networks:
  polar-net:
    driver: bridge